name: Create Release
on:
  workflow_dispatch:
    inputs:
      nextVersion:
        description: "New version to push"
        required: true
        default: "0.0.0"

      skipPreBuild:
        description: "Skip updating cargo.toml and committing new version"
        type: boolean
        required: false
        default: false

      preRelease:
        description: "Create a pre-release"
        type: boolean
        required: false
        default: false

jobs:
  pre-build:
    if: ${{ !inputs.skipPreBuild }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: moonrepo/setup-rust@v1

      - name: Install toml-cli
        run: cargo install toml-cli

      - name: Update Cargo.toml with new version
        # piping the output of toml-cli directly into the file will cause the file to be deleted before being read
        # by toml-cli. excuse this workaround.
        run: |
          toml set Cargo.toml package.version ${{inputs.nextVersion}} > Cargo.toml.tmp
          rm Cargo.toml
          mv Cargo.toml.tmp Cargo.toml
          cargo generate-lockfile

      - name: Push updated version
        run: |
          git config user.name "reliquary-archiver bot"
          git config user.email "reliquary-archiver.bot@users.noreply.github.com"

          git add Cargo.toml Cargo.lock
          git commit -m "[skip ci] bump version to v${{inputs.nextVersion}}"
          git push origin main

  build:
    needs: [pre-build]
    if: ${{ !cancelled() && (needs.pre-build.result == 'success' || needs.pre-build.result == 'skipped') }}
    strategy:
      fail-fast: false

      matrix:
        include:
          - name: reliquary-archiver-pcap-x64.exe
            os: windows-latest
            platform: windows
            features: "pcap,stream,gui"

          - name: reliquary-archiver-pktmon-x64.exe
            os: windows-latest
            platform: windows
            features: "pktmon,stream,gui"

          - name: reliquary-archiver-x64.AppImage
            os: ubuntu-latest
            platform: linux
            features: "pcap,stream"

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: moonrepo/setup-rust@v1

      - name: Install linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update 
          sudo apt install -y libpcap-dev libwayland-dev

      - name: Download and extract npcap
        if: matrix.platform == 'windows'
        run: |
          curl --silent --show-error --fail -o ./npcap-sdk.zip "https://npcap.com/dist/npcap-sdk-1.13.zip"
          unzip -p npcap-sdk.zip Lib/x64/Packet.lib > Packet.lib
          unzip -p npcap-sdk.zip Lib/x64/wpcap.lib > wpcap.lib

      - name: Build "${{ matrix.name }}"
        run: cargo build --release --no-default-features --features "${{ matrix.features }}"

      - name: Move "${{ matrix.name }}"
        if: matrix.platform == 'windows'
        run: mv -Force target/release/reliquary-archiver.exe "${{ matrix.name }}"

      - name: Pack "${{ matrix.name }}"
        if: matrix.platform == 'linux'
        run: |
          chmod +x build_appimage.bash
          ./build_appimage.bash "${{ matrix.name }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.name }}"
          path: "${{ matrix.name }}"
          if-no-files-found: error

  create-release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          pattern: reliquary-archiver-*

      - name: Create and push version tag
        run: |
          git tag v${{inputs.nextVersion}}
          git push origin --tags

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{inputs.nextVersion}}
          name: "v${{inputs.nextVersion}}"
          artifacts: artifacts/*
          prerelease: ${{ inputs.preRelease }}
